-- =========================================================================
-- NADS.IO - SUPABASE SQL SCHEMA & INITIALIZATION SCRIPT
-- =========================================================================
-- This script sets up the Database tables, Row Level Security (RLS) policies,
-- automatic User Profile triggers, and storage buckets required for Nads.io.
-- Run this script inside the SQL Editor of your Supabase Dashboard.

-- -------------------------------------------------------------------------
-- 1. Create Profiles Table
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  bio TEXT,
  is_glowing BOOLEAN DEFAULT true NOT NULL,
  avatar_url TEXT,
  banner_url TEXT,
  audio_url TEXT,
  audio_title TEXT,
  video_background_url TEXT,
  video_background_enabled BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- -------------------------------------------------------------------------
-- 2. Create Links Table
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  order_index INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- -------------------------------------------------------------------------
-- 3. Row Level Security Policies (RLS)
-- -------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.links ENABLE ROW LEVEL SECURITY;

-- Public read access to profiles
CREATE POLICY "Public profiles are viewable by everyone." 
  ON public.profiles FOR SELECT 
  USING (true);

-- User can insert their own profile
CREATE POLICY "Users can create their own profile." 
  ON public.profiles FOR INSERT 
  WITH CHECK (auth.uid() = id);

-- User can update their own profile
CREATE POLICY "Users can update their own profile." 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

-- Public read access to links
CREATE POLICY "Links are viewable by everyone." 
  ON public.links FOR SELECT 
  USING (true);

-- User can insert links to their profile
CREATE POLICY "Users can create links for their profile." 
  ON public.links FOR INSERT 
  WITH CHECK (auth.uid() = profile_id);

-- User can update their own links
CREATE POLICY "Users can update their own links." 
  ON public.links FOR UPDATE 
  USING (auth.uid() = profile_id);

-- User can delete their own links
CREATE POLICY "Users can delete their own links." 
  ON public.links FOR DELETE 
  USING (auth.uid() = profile_id);

-- -------------------------------------------------------------------------
-- 4. User Creation Synchronization Trigger
-- -------------------------------------------------------------------------
-- Automatically creates a matching profile in public.profiles when an user
-- signs up via Supabase Auth (e.g. Email/Password, Google, Discord).
-- It generates an automatically unique-deduplicated username based on email/meta.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  base_username TEXT;
  temp_username TEXT;
  counter INT := 0;
BEGIN
  -- Extract base username from custom metadata or email, removing non-alphanumeric chars
  base_username := LOWER(REGEXP_REPLACE(
    COALESCE(
      new.raw_user_meta_data->>'custom_username',
      new.raw_user_meta_data->>'name',
      SPLIT_PART(new.email, '@', 1)
    ),
    '[^a-zA-Z0-9]', '', 'g'
  ));
  
  -- Fallback if empty
  IF base_username IS NULL OR base_username = '' THEN
    base_username := 'user';
  END IF;

  temp_username := base_username;
  
  -- Prevent database unique key violations by checking existence and appending counter
  WHILE EXISTS (SELECT 1 FROM public.profiles WHERE username = temp_username) LOOP
    counter := counter + 1;
    temp_username := base_username || counter::text;
  END LOOP;

  INSERT INTO public.profiles (
    id,
    username,
    display_name,
    is_glowing,
    avatar_url,
    banner_url,
    audio_url,
    audio_title,
    video_background_url,
    video_background_enabled
  )
  VALUES (
    new.id,
    temp_username,
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', SPLIT_PART(new.email, '@', 1)),
    true,
    COALESCE(new.raw_user_meta_data->>'avatar_url', ''),
    '',
    '',
    '',
    '',
    false
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind trigger to auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- -------------------------------------------------------------------------
-- 5. Storage Buckets and Policies
-- -------------------------------------------------------------------------
-- These buckets are used for storing uploaded custom avatar icons, profiles' banner images, and MP3 audio track uploads.

-- Initialize storage buckets
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true) 
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('banners', 'banners', true) 
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('audio', 'audio', true) 
ON CONFLICT (id) DO NOTHING;

-- Avatars Storage policies
CREATE POLICY "Avatar images are publicly accessible." 
  ON storage.objects FOR SELECT 
  USING ( bucket_id = 'avatars' );

CREATE POLICY "Anyone can upload an avatar." 
  ON storage.objects FOR INSERT 
  WITH CHECK ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can update their avatar."
  ON storage.objects FOR UPDATE
  USING ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can delete their avatar."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );

-- Banners Storage policies
CREATE POLICY "Banner images are publicly accessible." 
  ON storage.objects FOR SELECT 
  USING ( bucket_id = 'banners' );

CREATE POLICY "Anyone can upload a banner." 
  ON storage.objects FOR INSERT 
  WITH CHECK ( bucket_id = 'banners' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can update their banner."
  ON storage.objects FOR UPDATE
  USING ( bucket_id = 'banners' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can delete their banner."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'banners' AND auth.role() = 'authenticated' );

-- Audio Storage policies
CREATE POLICY "Audio files are publicly accessible." 
  ON storage.objects FOR SELECT 
  USING ( bucket_id = 'audio' );

CREATE POLICY "Anyone can upload audio." 
  ON storage.objects FOR INSERT 
  WITH CHECK ( bucket_id = 'audio' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can update their audio."
  ON storage.objects FOR UPDATE
  USING ( bucket_id = 'audio' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can delete their audio."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'audio' AND auth.role() = 'authenticated' );
