-- Create Profiles Table
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  bio TEXT,
  is_glowing BOOLEAN DEFAULT true,
  avatar_url TEXT,
  banner_url TEXT,
  audio_url TEXT,
  audio_title TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Create Links Table
CREATE TABLE public.links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Turn on Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.links ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- Profiles RLS Policies
-- -------------------------------------------------------------
-- Public read access to profiles
CREATE POLICY "Public profiles are viewable by everyone." 
  ON public.profiles FOR SELECT 
  USING (true);

-- User can insert their own profile
CREATE POLICY "Users can create their own profile." 
  ON public.profiles FOR INSERT 
  WITH CHECK (auth.uid() = id);

-- User can update their own profile
CREATE POLICY "Users can update their own profile." 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

-- -------------------------------------------------------------
-- Links RLS Policies
-- -------------------------------------------------------------
-- Public read access to links
CREATE POLICY "Links are viewable by everyone." 
  ON public.links FOR SELECT 
  USING (true);

-- User can insert links to their profile
CREATE POLICY "Users can create links for their profile." 
  ON public.links FOR INSERT 
  WITH CHECK (auth.uid() = profile_id);

-- User can update their own links
CREATE POLICY "Users can update their own links." 
  ON public.links FOR UPDATE 
  USING (auth.uid() = profile_id);

-- User can delete their own links
CREATE POLICY "Users can delete their own links." 
  ON public.links FOR DELETE 
  USING (auth.uid() = profile_id);

-- -------------------------------------------------------------
-- Storage Setup
-- -------------------------------------------------------------
-- You need to create buckets in the Supabase Storage UI, or using SQL:
INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('banners', 'banners', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('audio', 'audio', true) ON CONFLICT DO NOTHING;

-- Avatars Storage RLS
CREATE POLICY "Avatar images are publicly accessible." 
  ON storage.objects FOR SELECT 
  USING ( bucket_id = 'avatars' );

CREATE POLICY "Anyone can upload an avatar." 
  ON storage.objects FOR INSERT 
  WITH CHECK ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can update their avatar."
  ON storage.objects FOR UPDATE
  USING ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can delete their avatar."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );

-- Banners Storage RLS
CREATE POLICY "Banner images are publicly accessible." 
  ON storage.objects FOR SELECT 
  USING ( bucket_id = 'banners' );

CREATE POLICY "Anyone can upload a banner." 
  ON storage.objects FOR INSERT 
  WITH CHECK ( bucket_id = 'banners' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can update their banner."
  ON storage.objects FOR UPDATE
  USING ( bucket_id = 'banners' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can delete their banner."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'banners' AND auth.role() = 'authenticated' );

-- Audio Storage RLS
CREATE POLICY "Audio files are publicly accessible." 
  ON storage.objects FOR SELECT 
  USING ( bucket_id = 'audio' );

CREATE POLICY "Anyone can upload audio." 
  ON storage.objects FOR INSERT 
  WITH CHECK ( bucket_id = 'audio' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can update their audio."
  ON storage.objects FOR UPDATE
  USING ( bucket_id = 'audio' AND auth.role() = 'authenticated' );

CREATE POLICY "Anyone can delete their audio."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'audio' AND auth.role() = 'authenticated' );

